# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/predator/Documents/Project/temp/libwebsockets

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/predator/Documents/Project/temp/libwebsockets

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/predator/Documents/Project/temp/libwebsockets/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\" \"dev\" \"examples\" \"libraries\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: all
	$(Q)./scripts/status.sh 1200 "scons"
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test-fuzxy

# Build rule for target.
test-fuzxy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-fuzxy
.PHONY : test-fuzxy

# fast build rule for target.
test-fuzxy/fast:
	$(MAKE) -f CMakeFiles/test-fuzxy.dir/build.make CMakeFiles/test-fuzxy.dir/build
.PHONY : test-fuzxy/fast

#=============================================================================
# Target rules for targets named test-server

# Build rule for target.
test-server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-server
.PHONY : test-server

# fast build rule for target.
test-server/fast:
	$(MAKE) -f CMakeFiles/test-server.dir/build.make CMakeFiles/test-server.dir/build
.PHONY : test-server/fast

#=============================================================================
# Target rules for targets named websockets_shared

# Build rule for target.
websockets_shared: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 websockets_shared
.PHONY : websockets_shared

# fast build rule for target.
websockets_shared/fast:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/build
.PHONY : websockets_shared/fast

#=============================================================================
# Target rules for targets named websockets

# Build rule for target.
websockets: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 websockets
.PHONY : websockets

# fast build rule for target.
websockets/fast:
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/build
.PHONY : websockets/fast

#=============================================================================
# Target rules for targets named test-fraggle

# Build rule for target.
test-fraggle: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-fraggle
.PHONY : test-fraggle

# fast build rule for target.
test-fraggle/fast:
	$(MAKE) -f CMakeFiles/test-fraggle.dir/build.make CMakeFiles/test-fraggle.dir/build
.PHONY : test-fraggle/fast

#=============================================================================
# Target rules for targets named dist

# Build rule for target.
dist: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dist
.PHONY : dist

# fast build rule for target.
dist/fast:
	$(MAKE) -f CMakeFiles/dist.dir/build.make CMakeFiles/dist.dir/build
.PHONY : dist/fast

#=============================================================================
# Target rules for targets named test-ping

# Build rule for target.
test-ping: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-ping
.PHONY : test-ping

# fast build rule for target.
test-ping/fast:
	$(MAKE) -f CMakeFiles/test-ping.dir/build.make CMakeFiles/test-ping.dir/build
.PHONY : test-ping/fast

#=============================================================================
# Target rules for targets named test-server-extpoll

# Build rule for target.
test-server-extpoll: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-server-extpoll
.PHONY : test-server-extpoll

# fast build rule for target.
test-server-extpoll/fast:
	$(MAKE) -f CMakeFiles/test-server-extpoll.dir/build.make CMakeFiles/test-server-extpoll.dir/build
.PHONY : test-server-extpoll/fast

#=============================================================================
# Target rules for targets named test-echo

# Build rule for target.
test-echo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-echo
.PHONY : test-echo

# fast build rule for target.
test-echo/fast:
	$(MAKE) -f CMakeFiles/test-echo.dir/build.make CMakeFiles/test-echo.dir/build
.PHONY : test-echo/fast

#=============================================================================
# Target rules for targets named test-server-pthreads

# Build rule for target.
test-server-pthreads: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-server-pthreads
.PHONY : test-server-pthreads

# fast build rule for target.
test-server-pthreads/fast:
	$(MAKE) -f CMakeFiles/test-server-pthreads.dir/build.make CMakeFiles/test-server-pthreads.dir/build
.PHONY : test-server-pthreads/fast

#=============================================================================
# Target rules for targets named test-client

# Build rule for target.
test-client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-client
.PHONY : test-client

# fast build rule for target.
test-client/fast:
	$(MAKE) -f CMakeFiles/test-client.dir/build.make CMakeFiles/test-client.dir/build
.PHONY : test-client/fast

lib/alloc.o: lib/alloc.c.o

.PHONY : lib/alloc.o

# target to build an object file
lib/alloc.c.o:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/alloc.c.o
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/alloc.c.o
.PHONY : lib/alloc.c.o

lib/alloc.i: lib/alloc.c.i

.PHONY : lib/alloc.i

# target to preprocess a source file
lib/alloc.c.i:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/alloc.c.i
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/alloc.c.i
.PHONY : lib/alloc.c.i

lib/alloc.s: lib/alloc.c.s

.PHONY : lib/alloc.s

# target to generate assembly for a file
lib/alloc.c.s:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/alloc.c.s
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/alloc.c.s
.PHONY : lib/alloc.c.s

lib/client/client-handshake.o: lib/client/client-handshake.c.o

.PHONY : lib/client/client-handshake.o

# target to build an object file
lib/client/client-handshake.c.o:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/client/client-handshake.c.o
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/client/client-handshake.c.o
.PHONY : lib/client/client-handshake.c.o

lib/client/client-handshake.i: lib/client/client-handshake.c.i

.PHONY : lib/client/client-handshake.i

# target to preprocess a source file
lib/client/client-handshake.c.i:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/client/client-handshake.c.i
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/client/client-handshake.c.i
.PHONY : lib/client/client-handshake.c.i

lib/client/client-handshake.s: lib/client/client-handshake.c.s

.PHONY : lib/client/client-handshake.s

# target to generate assembly for a file
lib/client/client-handshake.c.s:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/client/client-handshake.c.s
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/client/client-handshake.c.s
.PHONY : lib/client/client-handshake.c.s

lib/client/client-parser.o: lib/client/client-parser.c.o

.PHONY : lib/client/client-parser.o

# target to build an object file
lib/client/client-parser.c.o:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/client/client-parser.c.o
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/client/client-parser.c.o
.PHONY : lib/client/client-parser.c.o

lib/client/client-parser.i: lib/client/client-parser.c.i

.PHONY : lib/client/client-parser.i

# target to preprocess a source file
lib/client/client-parser.c.i:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/client/client-parser.c.i
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/client/client-parser.c.i
.PHONY : lib/client/client-parser.c.i

lib/client/client-parser.s: lib/client/client-parser.c.s

.PHONY : lib/client/client-parser.s

# target to generate assembly for a file
lib/client/client-parser.c.s:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/client/client-parser.c.s
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/client/client-parser.c.s
.PHONY : lib/client/client-parser.c.s

lib/client/client.o: lib/client/client.c.o

.PHONY : lib/client/client.o

# target to build an object file
lib/client/client.c.o:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/client/client.c.o
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/client/client.c.o
.PHONY : lib/client/client.c.o

lib/client/client.i: lib/client/client.c.i

.PHONY : lib/client/client.i

# target to preprocess a source file
lib/client/client.c.i:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/client/client.c.i
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/client/client.c.i
.PHONY : lib/client/client.c.i

lib/client/client.s: lib/client/client.c.s

.PHONY : lib/client/client.s

# target to generate assembly for a file
lib/client/client.c.s:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/client/client.c.s
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/client/client.c.s
.PHONY : lib/client/client.c.s

lib/client/ssl-client.o: lib/client/ssl-client.c.o

.PHONY : lib/client/ssl-client.o

# target to build an object file
lib/client/ssl-client.c.o:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/client/ssl-client.c.o
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/client/ssl-client.c.o
.PHONY : lib/client/ssl-client.c.o

lib/client/ssl-client.i: lib/client/ssl-client.c.i

.PHONY : lib/client/ssl-client.i

# target to preprocess a source file
lib/client/ssl-client.c.i:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/client/ssl-client.c.i
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/client/ssl-client.c.i
.PHONY : lib/client/ssl-client.c.i

lib/client/ssl-client.s: lib/client/ssl-client.c.s

.PHONY : lib/client/ssl-client.s

# target to generate assembly for a file
lib/client/ssl-client.c.s:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/client/ssl-client.c.s
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/client/ssl-client.c.s
.PHONY : lib/client/ssl-client.c.s

lib/context.o: lib/context.c.o

.PHONY : lib/context.o

# target to build an object file
lib/context.c.o:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/context.c.o
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/context.c.o
.PHONY : lib/context.c.o

lib/context.i: lib/context.c.i

.PHONY : lib/context.i

# target to preprocess a source file
lib/context.c.i:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/context.c.i
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/context.c.i
.PHONY : lib/context.c.i

lib/context.s: lib/context.c.s

.PHONY : lib/context.s

# target to generate assembly for a file
lib/context.c.s:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/context.c.s
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/context.c.s
.PHONY : lib/context.c.s

lib/handshake.o: lib/handshake.c.o

.PHONY : lib/handshake.o

# target to build an object file
lib/handshake.c.o:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/handshake.c.o
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/handshake.c.o
.PHONY : lib/handshake.c.o

lib/handshake.i: lib/handshake.c.i

.PHONY : lib/handshake.i

# target to preprocess a source file
lib/handshake.c.i:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/handshake.c.i
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/handshake.c.i
.PHONY : lib/handshake.c.i

lib/handshake.s: lib/handshake.c.s

.PHONY : lib/handshake.s

# target to generate assembly for a file
lib/handshake.c.s:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/handshake.c.s
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/handshake.c.s
.PHONY : lib/handshake.c.s

lib/header.o: lib/header.c.o

.PHONY : lib/header.o

# target to build an object file
lib/header.c.o:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/header.c.o
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/header.c.o
.PHONY : lib/header.c.o

lib/header.i: lib/header.c.i

.PHONY : lib/header.i

# target to preprocess a source file
lib/header.c.i:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/header.c.i
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/header.c.i
.PHONY : lib/header.c.i

lib/header.s: lib/header.c.s

.PHONY : lib/header.s

# target to generate assembly for a file
lib/header.c.s:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/header.c.s
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/header.c.s
.PHONY : lib/header.c.s

lib/libwebsockets.o: lib/libwebsockets.c.o

.PHONY : lib/libwebsockets.o

# target to build an object file
lib/libwebsockets.c.o:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/libwebsockets.c.o
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/libwebsockets.c.o
.PHONY : lib/libwebsockets.c.o

lib/libwebsockets.i: lib/libwebsockets.c.i

.PHONY : lib/libwebsockets.i

# target to preprocess a source file
lib/libwebsockets.c.i:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/libwebsockets.c.i
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/libwebsockets.c.i
.PHONY : lib/libwebsockets.c.i

lib/libwebsockets.s: lib/libwebsockets.c.s

.PHONY : lib/libwebsockets.s

# target to generate assembly for a file
lib/libwebsockets.c.s:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/libwebsockets.c.s
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/libwebsockets.c.s
.PHONY : lib/libwebsockets.c.s

lib/misc/base64-decode.o: lib/misc/base64-decode.c.o

.PHONY : lib/misc/base64-decode.o

# target to build an object file
lib/misc/base64-decode.c.o:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/misc/base64-decode.c.o
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/misc/base64-decode.c.o
.PHONY : lib/misc/base64-decode.c.o

lib/misc/base64-decode.i: lib/misc/base64-decode.c.i

.PHONY : lib/misc/base64-decode.i

# target to preprocess a source file
lib/misc/base64-decode.c.i:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/misc/base64-decode.c.i
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/misc/base64-decode.c.i
.PHONY : lib/misc/base64-decode.c.i

lib/misc/base64-decode.s: lib/misc/base64-decode.c.s

.PHONY : lib/misc/base64-decode.s

# target to generate assembly for a file
lib/misc/base64-decode.c.s:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/misc/base64-decode.c.s
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/misc/base64-decode.c.s
.PHONY : lib/misc/base64-decode.c.s

lib/misc/lws-ring.o: lib/misc/lws-ring.c.o

.PHONY : lib/misc/lws-ring.o

# target to build an object file
lib/misc/lws-ring.c.o:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/misc/lws-ring.c.o
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/misc/lws-ring.c.o
.PHONY : lib/misc/lws-ring.c.o

lib/misc/lws-ring.i: lib/misc/lws-ring.c.i

.PHONY : lib/misc/lws-ring.i

# target to preprocess a source file
lib/misc/lws-ring.c.i:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/misc/lws-ring.c.i
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/misc/lws-ring.c.i
.PHONY : lib/misc/lws-ring.c.i

lib/misc/lws-ring.s: lib/misc/lws-ring.c.s

.PHONY : lib/misc/lws-ring.s

# target to generate assembly for a file
lib/misc/lws-ring.c.s:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/misc/lws-ring.c.s
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/misc/lws-ring.c.s
.PHONY : lib/misc/lws-ring.c.s

lib/misc/sha-1.o: lib/misc/sha-1.c.o

.PHONY : lib/misc/sha-1.o

# target to build an object file
lib/misc/sha-1.c.o:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/misc/sha-1.c.o
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/misc/sha-1.c.o
.PHONY : lib/misc/sha-1.c.o

lib/misc/sha-1.i: lib/misc/sha-1.c.i

.PHONY : lib/misc/sha-1.i

# target to preprocess a source file
lib/misc/sha-1.c.i:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/misc/sha-1.c.i
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/misc/sha-1.c.i
.PHONY : lib/misc/sha-1.c.i

lib/misc/sha-1.s: lib/misc/sha-1.c.s

.PHONY : lib/misc/sha-1.s

# target to generate assembly for a file
lib/misc/sha-1.c.s:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/misc/sha-1.c.s
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/misc/sha-1.c.s
.PHONY : lib/misc/sha-1.c.s

lib/output.o: lib/output.c.o

.PHONY : lib/output.o

# target to build an object file
lib/output.c.o:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/output.c.o
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/output.c.o
.PHONY : lib/output.c.o

lib/output.i: lib/output.c.i

.PHONY : lib/output.i

# target to preprocess a source file
lib/output.c.i:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/output.c.i
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/output.c.i
.PHONY : lib/output.c.i

lib/output.s: lib/output.c.s

.PHONY : lib/output.s

# target to generate assembly for a file
lib/output.c.s:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/output.c.s
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/output.c.s
.PHONY : lib/output.c.s

lib/plat/lws-plat-unix.o: lib/plat/lws-plat-unix.c.o

.PHONY : lib/plat/lws-plat-unix.o

# target to build an object file
lib/plat/lws-plat-unix.c.o:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/plat/lws-plat-unix.c.o
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/plat/lws-plat-unix.c.o
.PHONY : lib/plat/lws-plat-unix.c.o

lib/plat/lws-plat-unix.i: lib/plat/lws-plat-unix.c.i

.PHONY : lib/plat/lws-plat-unix.i

# target to preprocess a source file
lib/plat/lws-plat-unix.c.i:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/plat/lws-plat-unix.c.i
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/plat/lws-plat-unix.c.i
.PHONY : lib/plat/lws-plat-unix.c.i

lib/plat/lws-plat-unix.s: lib/plat/lws-plat-unix.c.s

.PHONY : lib/plat/lws-plat-unix.s

# target to generate assembly for a file
lib/plat/lws-plat-unix.c.s:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/plat/lws-plat-unix.c.s
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/plat/lws-plat-unix.c.s
.PHONY : lib/plat/lws-plat-unix.c.s

lib/pollfd.o: lib/pollfd.c.o

.PHONY : lib/pollfd.o

# target to build an object file
lib/pollfd.c.o:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/pollfd.c.o
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/pollfd.c.o
.PHONY : lib/pollfd.c.o

lib/pollfd.i: lib/pollfd.c.i

.PHONY : lib/pollfd.i

# target to preprocess a source file
lib/pollfd.c.i:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/pollfd.c.i
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/pollfd.c.i
.PHONY : lib/pollfd.c.i

lib/pollfd.s: lib/pollfd.c.s

.PHONY : lib/pollfd.s

# target to generate assembly for a file
lib/pollfd.c.s:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/pollfd.c.s
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/pollfd.c.s
.PHONY : lib/pollfd.c.s

lib/server/lws-spa.o: lib/server/lws-spa.c.o

.PHONY : lib/server/lws-spa.o

# target to build an object file
lib/server/lws-spa.c.o:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/server/lws-spa.c.o
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/server/lws-spa.c.o
.PHONY : lib/server/lws-spa.c.o

lib/server/lws-spa.i: lib/server/lws-spa.c.i

.PHONY : lib/server/lws-spa.i

# target to preprocess a source file
lib/server/lws-spa.c.i:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/server/lws-spa.c.i
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/server/lws-spa.c.i
.PHONY : lib/server/lws-spa.c.i

lib/server/lws-spa.s: lib/server/lws-spa.c.s

.PHONY : lib/server/lws-spa.s

# target to generate assembly for a file
lib/server/lws-spa.c.s:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/server/lws-spa.c.s
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/server/lws-spa.c.s
.PHONY : lib/server/lws-spa.c.s

lib/server/parsers.o: lib/server/parsers.c.o

.PHONY : lib/server/parsers.o

# target to build an object file
lib/server/parsers.c.o:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/server/parsers.c.o
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/server/parsers.c.o
.PHONY : lib/server/parsers.c.o

lib/server/parsers.i: lib/server/parsers.c.i

.PHONY : lib/server/parsers.i

# target to preprocess a source file
lib/server/parsers.c.i:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/server/parsers.c.i
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/server/parsers.c.i
.PHONY : lib/server/parsers.c.i

lib/server/parsers.s: lib/server/parsers.c.s

.PHONY : lib/server/parsers.s

# target to generate assembly for a file
lib/server/parsers.c.s:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/server/parsers.c.s
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/server/parsers.c.s
.PHONY : lib/server/parsers.c.s

lib/server/server-handshake.o: lib/server/server-handshake.c.o

.PHONY : lib/server/server-handshake.o

# target to build an object file
lib/server/server-handshake.c.o:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/server/server-handshake.c.o
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/server/server-handshake.c.o
.PHONY : lib/server/server-handshake.c.o

lib/server/server-handshake.i: lib/server/server-handshake.c.i

.PHONY : lib/server/server-handshake.i

# target to preprocess a source file
lib/server/server-handshake.c.i:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/server/server-handshake.c.i
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/server/server-handshake.c.i
.PHONY : lib/server/server-handshake.c.i

lib/server/server-handshake.s: lib/server/server-handshake.c.s

.PHONY : lib/server/server-handshake.s

# target to generate assembly for a file
lib/server/server-handshake.c.s:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/server/server-handshake.c.s
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/server/server-handshake.c.s
.PHONY : lib/server/server-handshake.c.s

lib/server/server.o: lib/server/server.c.o

.PHONY : lib/server/server.o

# target to build an object file
lib/server/server.c.o:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/server/server.c.o
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/server/server.c.o
.PHONY : lib/server/server.c.o

lib/server/server.i: lib/server/server.c.i

.PHONY : lib/server/server.i

# target to preprocess a source file
lib/server/server.c.i:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/server/server.c.i
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/server/server.c.i
.PHONY : lib/server/server.c.i

lib/server/server.s: lib/server/server.c.s

.PHONY : lib/server/server.s

# target to generate assembly for a file
lib/server/server.c.s:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/server/server.c.s
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/server/server.c.s
.PHONY : lib/server/server.c.s

lib/server/ssl-server.o: lib/server/ssl-server.c.o

.PHONY : lib/server/ssl-server.o

# target to build an object file
lib/server/ssl-server.c.o:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/server/ssl-server.c.o
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/server/ssl-server.c.o
.PHONY : lib/server/ssl-server.c.o

lib/server/ssl-server.i: lib/server/ssl-server.c.i

.PHONY : lib/server/ssl-server.i

# target to preprocess a source file
lib/server/ssl-server.c.i:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/server/ssl-server.c.i
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/server/ssl-server.c.i
.PHONY : lib/server/ssl-server.c.i

lib/server/ssl-server.s: lib/server/ssl-server.c.s

.PHONY : lib/server/ssl-server.s

# target to generate assembly for a file
lib/server/ssl-server.c.s:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/server/ssl-server.c.s
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/server/ssl-server.c.s
.PHONY : lib/server/ssl-server.c.s

lib/service.o: lib/service.c.o

.PHONY : lib/service.o

# target to build an object file
lib/service.c.o:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/service.c.o
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/service.c.o
.PHONY : lib/service.c.o

lib/service.i: lib/service.c.i

.PHONY : lib/service.i

# target to preprocess a source file
lib/service.c.i:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/service.c.i
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/service.c.i
.PHONY : lib/service.c.i

lib/service.s: lib/service.c.s

.PHONY : lib/service.s

# target to generate assembly for a file
lib/service.c.s:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/service.c.s
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/service.c.s
.PHONY : lib/service.c.s

lib/tls/openssl/openssl-client.o: lib/tls/openssl/openssl-client.c.o

.PHONY : lib/tls/openssl/openssl-client.o

# target to build an object file
lib/tls/openssl/openssl-client.c.o:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/tls/openssl/openssl-client.c.o
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/tls/openssl/openssl-client.c.o
.PHONY : lib/tls/openssl/openssl-client.c.o

lib/tls/openssl/openssl-client.i: lib/tls/openssl/openssl-client.c.i

.PHONY : lib/tls/openssl/openssl-client.i

# target to preprocess a source file
lib/tls/openssl/openssl-client.c.i:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/tls/openssl/openssl-client.c.i
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/tls/openssl/openssl-client.c.i
.PHONY : lib/tls/openssl/openssl-client.c.i

lib/tls/openssl/openssl-client.s: lib/tls/openssl/openssl-client.c.s

.PHONY : lib/tls/openssl/openssl-client.s

# target to generate assembly for a file
lib/tls/openssl/openssl-client.c.s:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/tls/openssl/openssl-client.c.s
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/tls/openssl/openssl-client.c.s
.PHONY : lib/tls/openssl/openssl-client.c.s

lib/tls/openssl/openssl-server.o: lib/tls/openssl/openssl-server.c.o

.PHONY : lib/tls/openssl/openssl-server.o

# target to build an object file
lib/tls/openssl/openssl-server.c.o:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/tls/openssl/openssl-server.c.o
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/tls/openssl/openssl-server.c.o
.PHONY : lib/tls/openssl/openssl-server.c.o

lib/tls/openssl/openssl-server.i: lib/tls/openssl/openssl-server.c.i

.PHONY : lib/tls/openssl/openssl-server.i

# target to preprocess a source file
lib/tls/openssl/openssl-server.c.i:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/tls/openssl/openssl-server.c.i
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/tls/openssl/openssl-server.c.i
.PHONY : lib/tls/openssl/openssl-server.c.i

lib/tls/openssl/openssl-server.s: lib/tls/openssl/openssl-server.c.s

.PHONY : lib/tls/openssl/openssl-server.s

# target to generate assembly for a file
lib/tls/openssl/openssl-server.c.s:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/tls/openssl/openssl-server.c.s
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/tls/openssl/openssl-server.c.s
.PHONY : lib/tls/openssl/openssl-server.c.s

lib/tls/openssl/ssl.o: lib/tls/openssl/ssl.c.o

.PHONY : lib/tls/openssl/ssl.o

# target to build an object file
lib/tls/openssl/ssl.c.o:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/tls/openssl/ssl.c.o
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/tls/openssl/ssl.c.o
.PHONY : lib/tls/openssl/ssl.c.o

lib/tls/openssl/ssl.i: lib/tls/openssl/ssl.c.i

.PHONY : lib/tls/openssl/ssl.i

# target to preprocess a source file
lib/tls/openssl/ssl.c.i:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/tls/openssl/ssl.c.i
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/tls/openssl/ssl.c.i
.PHONY : lib/tls/openssl/ssl.c.i

lib/tls/openssl/ssl.s: lib/tls/openssl/ssl.c.s

.PHONY : lib/tls/openssl/ssl.s

# target to generate assembly for a file
lib/tls/openssl/ssl.c.s:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/tls/openssl/ssl.c.s
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/tls/openssl/ssl.c.s
.PHONY : lib/tls/openssl/ssl.c.s

lib/tls/tls.o: lib/tls/tls.c.o

.PHONY : lib/tls/tls.o

# target to build an object file
lib/tls/tls.c.o:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/tls/tls.c.o
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/tls/tls.c.o
.PHONY : lib/tls/tls.c.o

lib/tls/tls.i: lib/tls/tls.c.i

.PHONY : lib/tls/tls.i

# target to preprocess a source file
lib/tls/tls.c.i:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/tls/tls.c.i
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/tls/tls.c.i
.PHONY : lib/tls/tls.c.i

lib/tls/tls.s: lib/tls/tls.c.s

.PHONY : lib/tls/tls.s

# target to generate assembly for a file
lib/tls/tls.c.s:
	$(MAKE) -f CMakeFiles/websockets_shared.dir/build.make CMakeFiles/websockets_shared.dir/lib/tls/tls.c.s
	$(MAKE) -f CMakeFiles/websockets.dir/build.make CMakeFiles/websockets.dir/lib/tls/tls.c.s
.PHONY : lib/tls/tls.c.s

test-apps/fuzxy.o: test-apps/fuzxy.c.o

.PHONY : test-apps/fuzxy.o

# target to build an object file
test-apps/fuzxy.c.o:
	$(MAKE) -f CMakeFiles/test-fuzxy.dir/build.make CMakeFiles/test-fuzxy.dir/test-apps/fuzxy.c.o
.PHONY : test-apps/fuzxy.c.o

test-apps/fuzxy.i: test-apps/fuzxy.c.i

.PHONY : test-apps/fuzxy.i

# target to preprocess a source file
test-apps/fuzxy.c.i:
	$(MAKE) -f CMakeFiles/test-fuzxy.dir/build.make CMakeFiles/test-fuzxy.dir/test-apps/fuzxy.c.i
.PHONY : test-apps/fuzxy.c.i

test-apps/fuzxy.s: test-apps/fuzxy.c.s

.PHONY : test-apps/fuzxy.s

# target to generate assembly for a file
test-apps/fuzxy.c.s:
	$(MAKE) -f CMakeFiles/test-fuzxy.dir/build.make CMakeFiles/test-fuzxy.dir/test-apps/fuzxy.c.s
.PHONY : test-apps/fuzxy.c.s

test-apps/test-client.o: test-apps/test-client.c.o

.PHONY : test-apps/test-client.o

# target to build an object file
test-apps/test-client.c.o:
	$(MAKE) -f CMakeFiles/test-client.dir/build.make CMakeFiles/test-client.dir/test-apps/test-client.c.o
.PHONY : test-apps/test-client.c.o

test-apps/test-client.i: test-apps/test-client.c.i

.PHONY : test-apps/test-client.i

# target to preprocess a source file
test-apps/test-client.c.i:
	$(MAKE) -f CMakeFiles/test-client.dir/build.make CMakeFiles/test-client.dir/test-apps/test-client.c.i
.PHONY : test-apps/test-client.c.i

test-apps/test-client.s: test-apps/test-client.c.s

.PHONY : test-apps/test-client.s

# target to generate assembly for a file
test-apps/test-client.c.s:
	$(MAKE) -f CMakeFiles/test-client.dir/build.make CMakeFiles/test-client.dir/test-apps/test-client.c.s
.PHONY : test-apps/test-client.c.s

test-apps/test-echo.o: test-apps/test-echo.c.o

.PHONY : test-apps/test-echo.o

# target to build an object file
test-apps/test-echo.c.o:
	$(MAKE) -f CMakeFiles/test-echo.dir/build.make CMakeFiles/test-echo.dir/test-apps/test-echo.c.o
.PHONY : test-apps/test-echo.c.o

test-apps/test-echo.i: test-apps/test-echo.c.i

.PHONY : test-apps/test-echo.i

# target to preprocess a source file
test-apps/test-echo.c.i:
	$(MAKE) -f CMakeFiles/test-echo.dir/build.make CMakeFiles/test-echo.dir/test-apps/test-echo.c.i
.PHONY : test-apps/test-echo.c.i

test-apps/test-echo.s: test-apps/test-echo.c.s

.PHONY : test-apps/test-echo.s

# target to generate assembly for a file
test-apps/test-echo.c.s:
	$(MAKE) -f CMakeFiles/test-echo.dir/build.make CMakeFiles/test-echo.dir/test-apps/test-echo.c.s
.PHONY : test-apps/test-echo.c.s

test-apps/test-fraggle.o: test-apps/test-fraggle.c.o

.PHONY : test-apps/test-fraggle.o

# target to build an object file
test-apps/test-fraggle.c.o:
	$(MAKE) -f CMakeFiles/test-fraggle.dir/build.make CMakeFiles/test-fraggle.dir/test-apps/test-fraggle.c.o
.PHONY : test-apps/test-fraggle.c.o

test-apps/test-fraggle.i: test-apps/test-fraggle.c.i

.PHONY : test-apps/test-fraggle.i

# target to preprocess a source file
test-apps/test-fraggle.c.i:
	$(MAKE) -f CMakeFiles/test-fraggle.dir/build.make CMakeFiles/test-fraggle.dir/test-apps/test-fraggle.c.i
.PHONY : test-apps/test-fraggle.c.i

test-apps/test-fraggle.s: test-apps/test-fraggle.c.s

.PHONY : test-apps/test-fraggle.s

# target to generate assembly for a file
test-apps/test-fraggle.c.s:
	$(MAKE) -f CMakeFiles/test-fraggle.dir/build.make CMakeFiles/test-fraggle.dir/test-apps/test-fraggle.c.s
.PHONY : test-apps/test-fraggle.c.s

test-apps/test-ping.o: test-apps/test-ping.c.o

.PHONY : test-apps/test-ping.o

# target to build an object file
test-apps/test-ping.c.o:
	$(MAKE) -f CMakeFiles/test-ping.dir/build.make CMakeFiles/test-ping.dir/test-apps/test-ping.c.o
.PHONY : test-apps/test-ping.c.o

test-apps/test-ping.i: test-apps/test-ping.c.i

.PHONY : test-apps/test-ping.i

# target to preprocess a source file
test-apps/test-ping.c.i:
	$(MAKE) -f CMakeFiles/test-ping.dir/build.make CMakeFiles/test-ping.dir/test-apps/test-ping.c.i
.PHONY : test-apps/test-ping.c.i

test-apps/test-ping.s: test-apps/test-ping.c.s

.PHONY : test-apps/test-ping.s

# target to generate assembly for a file
test-apps/test-ping.c.s:
	$(MAKE) -f CMakeFiles/test-ping.dir/build.make CMakeFiles/test-ping.dir/test-apps/test-ping.c.s
.PHONY : test-apps/test-ping.c.s

test-apps/test-server-dumb-increment.o: test-apps/test-server-dumb-increment.c.o

.PHONY : test-apps/test-server-dumb-increment.o

# target to build an object file
test-apps/test-server-dumb-increment.c.o:
	$(MAKE) -f CMakeFiles/test-server.dir/build.make CMakeFiles/test-server.dir/test-apps/test-server-dumb-increment.c.o
	$(MAKE) -f CMakeFiles/test-server-extpoll.dir/build.make CMakeFiles/test-server-extpoll.dir/test-apps/test-server-dumb-increment.c.o
	$(MAKE) -f CMakeFiles/test-server-pthreads.dir/build.make CMakeFiles/test-server-pthreads.dir/test-apps/test-server-dumb-increment.c.o
.PHONY : test-apps/test-server-dumb-increment.c.o

test-apps/test-server-dumb-increment.i: test-apps/test-server-dumb-increment.c.i

.PHONY : test-apps/test-server-dumb-increment.i

# target to preprocess a source file
test-apps/test-server-dumb-increment.c.i:
	$(MAKE) -f CMakeFiles/test-server.dir/build.make CMakeFiles/test-server.dir/test-apps/test-server-dumb-increment.c.i
	$(MAKE) -f CMakeFiles/test-server-extpoll.dir/build.make CMakeFiles/test-server-extpoll.dir/test-apps/test-server-dumb-increment.c.i
	$(MAKE) -f CMakeFiles/test-server-pthreads.dir/build.make CMakeFiles/test-server-pthreads.dir/test-apps/test-server-dumb-increment.c.i
.PHONY : test-apps/test-server-dumb-increment.c.i

test-apps/test-server-dumb-increment.s: test-apps/test-server-dumb-increment.c.s

.PHONY : test-apps/test-server-dumb-increment.s

# target to generate assembly for a file
test-apps/test-server-dumb-increment.c.s:
	$(MAKE) -f CMakeFiles/test-server.dir/build.make CMakeFiles/test-server.dir/test-apps/test-server-dumb-increment.c.s
	$(MAKE) -f CMakeFiles/test-server-extpoll.dir/build.make CMakeFiles/test-server-extpoll.dir/test-apps/test-server-dumb-increment.c.s
	$(MAKE) -f CMakeFiles/test-server-pthreads.dir/build.make CMakeFiles/test-server-pthreads.dir/test-apps/test-server-dumb-increment.c.s
.PHONY : test-apps/test-server-dumb-increment.c.s

test-apps/test-server-http.o: test-apps/test-server-http.c.o

.PHONY : test-apps/test-server-http.o

# target to build an object file
test-apps/test-server-http.c.o:
	$(MAKE) -f CMakeFiles/test-server.dir/build.make CMakeFiles/test-server.dir/test-apps/test-server-http.c.o
	$(MAKE) -f CMakeFiles/test-server-extpoll.dir/build.make CMakeFiles/test-server-extpoll.dir/test-apps/test-server-http.c.o
	$(MAKE) -f CMakeFiles/test-server-pthreads.dir/build.make CMakeFiles/test-server-pthreads.dir/test-apps/test-server-http.c.o
.PHONY : test-apps/test-server-http.c.o

test-apps/test-server-http.i: test-apps/test-server-http.c.i

.PHONY : test-apps/test-server-http.i

# target to preprocess a source file
test-apps/test-server-http.c.i:
	$(MAKE) -f CMakeFiles/test-server.dir/build.make CMakeFiles/test-server.dir/test-apps/test-server-http.c.i
	$(MAKE) -f CMakeFiles/test-server-extpoll.dir/build.make CMakeFiles/test-server-extpoll.dir/test-apps/test-server-http.c.i
	$(MAKE) -f CMakeFiles/test-server-pthreads.dir/build.make CMakeFiles/test-server-pthreads.dir/test-apps/test-server-http.c.i
.PHONY : test-apps/test-server-http.c.i

test-apps/test-server-http.s: test-apps/test-server-http.c.s

.PHONY : test-apps/test-server-http.s

# target to generate assembly for a file
test-apps/test-server-http.c.s:
	$(MAKE) -f CMakeFiles/test-server.dir/build.make CMakeFiles/test-server.dir/test-apps/test-server-http.c.s
	$(MAKE) -f CMakeFiles/test-server-extpoll.dir/build.make CMakeFiles/test-server-extpoll.dir/test-apps/test-server-http.c.s
	$(MAKE) -f CMakeFiles/test-server-pthreads.dir/build.make CMakeFiles/test-server-pthreads.dir/test-apps/test-server-http.c.s
.PHONY : test-apps/test-server-http.c.s

test-apps/test-server-pthreads.o: test-apps/test-server-pthreads.c.o

.PHONY : test-apps/test-server-pthreads.o

# target to build an object file
test-apps/test-server-pthreads.c.o:
	$(MAKE) -f CMakeFiles/test-server-pthreads.dir/build.make CMakeFiles/test-server-pthreads.dir/test-apps/test-server-pthreads.c.o
.PHONY : test-apps/test-server-pthreads.c.o

test-apps/test-server-pthreads.i: test-apps/test-server-pthreads.c.i

.PHONY : test-apps/test-server-pthreads.i

# target to preprocess a source file
test-apps/test-server-pthreads.c.i:
	$(MAKE) -f CMakeFiles/test-server-pthreads.dir/build.make CMakeFiles/test-server-pthreads.dir/test-apps/test-server-pthreads.c.i
.PHONY : test-apps/test-server-pthreads.c.i

test-apps/test-server-pthreads.s: test-apps/test-server-pthreads.c.s

.PHONY : test-apps/test-server-pthreads.s

# target to generate assembly for a file
test-apps/test-server-pthreads.c.s:
	$(MAKE) -f CMakeFiles/test-server-pthreads.dir/build.make CMakeFiles/test-server-pthreads.dir/test-apps/test-server-pthreads.c.s
.PHONY : test-apps/test-server-pthreads.c.s

test-apps/test-server.o: test-apps/test-server.c.o

.PHONY : test-apps/test-server.o

# target to build an object file
test-apps/test-server.c.o:
	$(MAKE) -f CMakeFiles/test-server.dir/build.make CMakeFiles/test-server.dir/test-apps/test-server.c.o
	$(MAKE) -f CMakeFiles/test-server-extpoll.dir/build.make CMakeFiles/test-server-extpoll.dir/test-apps/test-server.c.o
.PHONY : test-apps/test-server.c.o

test-apps/test-server.i: test-apps/test-server.c.i

.PHONY : test-apps/test-server.i

# target to preprocess a source file
test-apps/test-server.c.i:
	$(MAKE) -f CMakeFiles/test-server.dir/build.make CMakeFiles/test-server.dir/test-apps/test-server.c.i
	$(MAKE) -f CMakeFiles/test-server-extpoll.dir/build.make CMakeFiles/test-server-extpoll.dir/test-apps/test-server.c.i
.PHONY : test-apps/test-server.c.i

test-apps/test-server.s: test-apps/test-server.c.s

.PHONY : test-apps/test-server.s

# target to generate assembly for a file
test-apps/test-server.c.s:
	$(MAKE) -f CMakeFiles/test-server.dir/build.make CMakeFiles/test-server.dir/test-apps/test-server.c.s
	$(MAKE) -f CMakeFiles/test-server-extpoll.dir/build.make CMakeFiles/test-server-extpoll.dir/test-apps/test-server.c.s
.PHONY : test-apps/test-server.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... package_source"
	@echo "... package"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... install/strip"
	@echo "... test-fuzxy"
	@echo "... test-server"
	@echo "... edit_cache"
	@echo "... websockets_shared"
	@echo "... websockets"
	@echo "... test-fraggle"
	@echo "... install/local"
	@echo "... dist"
	@echo "... test-ping"
	@echo "... test-server-extpoll"
	@echo "... test-echo"
	@echo "... rebuild_cache"
	@echo "... test-server-pthreads"
	@echo "... test-client"
	@echo "... lib/alloc.o"
	@echo "... lib/alloc.i"
	@echo "... lib/alloc.s"
	@echo "... lib/client/client-handshake.o"
	@echo "... lib/client/client-handshake.i"
	@echo "... lib/client/client-handshake.s"
	@echo "... lib/client/client-parser.o"
	@echo "... lib/client/client-parser.i"
	@echo "... lib/client/client-parser.s"
	@echo "... lib/client/client.o"
	@echo "... lib/client/client.i"
	@echo "... lib/client/client.s"
	@echo "... lib/client/ssl-client.o"
	@echo "... lib/client/ssl-client.i"
	@echo "... lib/client/ssl-client.s"
	@echo "... lib/context.o"
	@echo "... lib/context.i"
	@echo "... lib/context.s"
	@echo "... lib/handshake.o"
	@echo "... lib/handshake.i"
	@echo "... lib/handshake.s"
	@echo "... lib/header.o"
	@echo "... lib/header.i"
	@echo "... lib/header.s"
	@echo "... lib/libwebsockets.o"
	@echo "... lib/libwebsockets.i"
	@echo "... lib/libwebsockets.s"
	@echo "... lib/misc/base64-decode.o"
	@echo "... lib/misc/base64-decode.i"
	@echo "... lib/misc/base64-decode.s"
	@echo "... lib/misc/lws-ring.o"
	@echo "... lib/misc/lws-ring.i"
	@echo "... lib/misc/lws-ring.s"
	@echo "... lib/misc/sha-1.o"
	@echo "... lib/misc/sha-1.i"
	@echo "... lib/misc/sha-1.s"
	@echo "... lib/output.o"
	@echo "... lib/output.i"
	@echo "... lib/output.s"
	@echo "... lib/plat/lws-plat-unix.o"
	@echo "... lib/plat/lws-plat-unix.i"
	@echo "... lib/plat/lws-plat-unix.s"
	@echo "... lib/pollfd.o"
	@echo "... lib/pollfd.i"
	@echo "... lib/pollfd.s"
	@echo "... lib/server/lws-spa.o"
	@echo "... lib/server/lws-spa.i"
	@echo "... lib/server/lws-spa.s"
	@echo "... lib/server/parsers.o"
	@echo "... lib/server/parsers.i"
	@echo "... lib/server/parsers.s"
	@echo "... lib/server/server-handshake.o"
	@echo "... lib/server/server-handshake.i"
	@echo "... lib/server/server-handshake.s"
	@echo "... lib/server/server.o"
	@echo "... lib/server/server.i"
	@echo "... lib/server/server.s"
	@echo "... lib/server/ssl-server.o"
	@echo "... lib/server/ssl-server.i"
	@echo "... lib/server/ssl-server.s"
	@echo "... lib/service.o"
	@echo "... lib/service.i"
	@echo "... lib/service.s"
	@echo "... lib/tls/openssl/openssl-client.o"
	@echo "... lib/tls/openssl/openssl-client.i"
	@echo "... lib/tls/openssl/openssl-client.s"
	@echo "... lib/tls/openssl/openssl-server.o"
	@echo "... lib/tls/openssl/openssl-server.i"
	@echo "... lib/tls/openssl/openssl-server.s"
	@echo "... lib/tls/openssl/ssl.o"
	@echo "... lib/tls/openssl/ssl.i"
	@echo "... lib/tls/openssl/ssl.s"
	@echo "... lib/tls/tls.o"
	@echo "... lib/tls/tls.i"
	@echo "... lib/tls/tls.s"
	@echo "... test-apps/fuzxy.o"
	@echo "... test-apps/fuzxy.i"
	@echo "... test-apps/fuzxy.s"
	@echo "... test-apps/test-client.o"
	@echo "... test-apps/test-client.i"
	@echo "... test-apps/test-client.s"
	@echo "... test-apps/test-echo.o"
	@echo "... test-apps/test-echo.i"
	@echo "... test-apps/test-echo.s"
	@echo "... test-apps/test-fraggle.o"
	@echo "... test-apps/test-fraggle.i"
	@echo "... test-apps/test-fraggle.s"
	@echo "... test-apps/test-ping.o"
	@echo "... test-apps/test-ping.i"
	@echo "... test-apps/test-ping.s"
	@echo "... test-apps/test-server-dumb-increment.o"
	@echo "... test-apps/test-server-dumb-increment.i"
	@echo "... test-apps/test-server-dumb-increment.s"
	@echo "... test-apps/test-server-http.o"
	@echo "... test-apps/test-server-http.i"
	@echo "... test-apps/test-server-http.s"
	@echo "... test-apps/test-server-pthreads.o"
	@echo "... test-apps/test-server-pthreads.i"
	@echo "... test-apps/test-server-pthreads.s"
	@echo "... test-apps/test-server.o"
	@echo "... test-apps/test-server.i"
	@echo "... test-apps/test-server.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

