version: 2
jobs:
  build-default:
    docker:
      - image: ubuntu:trusty
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get -y install build-essential
      - run: sudo apt-get -y install libelf-dev
      - run: sudo apt-get -y install wget
      - run: sudo apt-get -y install unzip
      - run: make version="--default" all
  build-with-ssl:
    docker:
      - image: ubuntu:trusty
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get -y install build-essential
      - run: sudo apt-get -y install libelf-dev
      - run: sudo apt-get -y install wget
      - run: sudo apt-get -y install unzip
      - run: make version="--with-ssl" all
  build-with-tls:
    docker:
      - image: ubuntu:trusty
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get -y install build-essential
      - run: sudo apt-get -y install libelf-dev
      - run: sudo apt-get -y install wget
      - run: sudo apt-get -y install unzip
      - run: make version="--with-tls" all
  build-debug:
    docker:
      - image: ubuntu:trusty
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get -y install build-essential
      - run: sudo apt-get -y install libelf-dev
      - run: sudo apt-get -y install wget
      - run: sudo apt-get -y install unzip
      - run: make version="--debug" all
workflows:
  version: 2
  libwebsockets_builds:
    jobs:
      - build-default
      - build-with-ssl
      - build-with-tls
      - build-debug

